// Package secrettaint tracks the runtime state of processes that have
// touched sensitive material (secrets, tokens, cloud metadata, kube
// service-account tokens, etc.) so the verifier, egressguard, and
// incidentgraph can apply stricter rules to descendant behavior.
//
// Architectural role: this is the "theft-toxic" subsystem. Once a
// lineage touches a secret class, novel outbound is restricted,
// persistence-like writes get higher scrutiny, and the incident scorer
// weights follow-on behavior accordingly.
//
// Phase B.2 of the BRP implementation plan
// (docs/BRP_IMPLEMENTATION_PLAN_2026-05-24.md). Build spec contract at
// docs/BRP_CORRELATION_BUILD_SPEC_2026-05-24.md §3.1.
//
// Key invariants:
//
//   - Taint never silently decays while lineage is active. Clear only
//     happens through ForgetReason events (process exit, operator
//     override, TTL expiry) — each logged.
//   - Parent→child propagation: a forked process inherits its parent's
//     taint state and class set.
//   - Concurrent-safe; the Store can be hit per-event without coarse
//     locking (per-lineage entry locks).
package secrettaint

import (
	"time"
)

// SecretClass enumerates the kinds of sensitive material a lineage can
// touch. Purpose-aware split per build spec §3.1; do NOT collapse back
// to a single "secret_file" catch-all.
type SecretClass string

const (
	SecretEnv              SecretClass = "env"
	SecretProcEnviron      SecretClass = "proc_environ"
	SecretCloudCreds       SecretClass = "cloud_creds"
	SecretKubeToken        SecretClass = "kube_token"
	SecretGitToken         SecretClass = "git_token"
	SecretAPIKey           SecretClass = "api_key"
	SecretBrowserSession   SecretClass = "browser_session"
	SecretSecretFile       SecretClass = "secret_file"
	SecretMetadata         SecretClass = "metadata"
	SecretSessionStore     SecretClass = "session_store"
	SecretWorkloadIdentity SecretClass = "workload_identity"
	SecretToken            SecretClass = "token"
)

// TaintState is the lineage-wide trust posture after secret access.
type TaintState uint8

const (
	// TaintClean: no secret has been touched by this lineage or any
	// ancestor. Default state.
	TaintClean TaintState = iota
	// TaintSecretTouched: lineage (or an ancestor) has read at least one
	// secret class. Default action: verifier sees the taint; egressguard
	// can choose to restrict novel outbound; incidentgraph weights
	// follow-on actions higher.
	TaintSecretTouched
	// TaintOutboundRestricted: lineage was promoted because it attempted
	// novel outbound after touching secrets. Default action: egressguard
	// hard-denies further novel destinations from this lineage.
	TaintOutboundRestricted
	// TaintContainmentRequired: lineage exceeded multiple trust gates
	// (e.g. secret + outbound + persistence). Default action: response
	// engine freezes the lineage; operator review required to release.
	TaintContainmentRequired
)

// String returns the canonical short token used in event tags + logs.
func (t TaintState) String() string {
	switch t {
	case TaintClean:
		return "clean"
	case TaintSecretTouched:
		return "secret_touched"
	case TaintOutboundRestricted:
		return "outbound_restricted"
	case TaintContainmentRequired:
		return "containment_required"
	}
	return "unknown"
}

// Touch is a single secret-access observation. Generated by the
// pipeline when an event matches a secret source (env read, metadata
// access, cloud creds file open, etc.) and consumed by Store.ObserveTouch.
type Touch struct {
	PID         uint32
	LineageID   uint64
	SourceID    uint64
	SecretClass SecretClass
	Path        string // optional; useful for audit
	At          time.Time
}

// ForgetReason is the audited reason for clearing taint on a lineage.
// Every Forget call MUST carry a reason so future review can audit
// taint clears (which are security-sensitive: a wrongly-cleared taint
// turns a stolen-secret lineage back into "normal" lineage).
type ForgetReason uint8

const (
	// ForgetLineageExit: the process exited normally. The taint cleanup
	// is the result of natural lineage end-of-life.
	ForgetLineageExit ForgetReason = iota
	// ForgetOperatorOverride: an operator explicitly cleared taint via
	// xhelixctl. Audit-logged at INFO with the operator identity.
	ForgetOperatorOverride
	// ForgetTTLExpiry: the taint exceeded the configured max-age. Used
	// to keep the store bounded across daemon lifetimes; default is
	// long enough that legitimate apps don't expire mid-session.
	ForgetTTLExpiry
)

// String returns the canonical short token used in audit logs.
func (r ForgetReason) String() string {
	switch r {
	case ForgetLineageExit:
		return "lineage_exit"
	case ForgetOperatorOverride:
		return "operator_override"
	case ForgetTTLExpiry:
		return "ttl_expiry"
	}
	return "unknown"
}

// Store is the runtime API for secret-taint state. Implementations
// must be safe for concurrent use. The default in-memory implementation
// is in store.go; see TestStore in the test file for behavior contracts.
type Store interface {
	// ObserveTouch records a secret-access observation. If the lineage
	// was clean, it transitions to TaintSecretTouched. If already in a
	// higher state (OutboundRestricted, ContainmentRequired), the touch
	// is appended to the class set but the state does not regress.
	ObserveTouch(Touch)

	// StateForLineage returns the current TaintState for the lineage.
	// Returns TaintClean if the lineage has never been touched or has
	// been forgotten.
	StateForLineage(uint64) TaintState

	// ClassesForLineage returns the set of secret classes touched by
	// this lineage and its ancestors. The slice is a copy; callers may
	// modify it without affecting store state. Empty slice for clean.
	ClassesForLineage(uint64) []SecretClass

	// PromoteOutboundRestricted moves the lineage from SecretTouched
	// to OutboundRestricted, recording the trigger event time + reason
	// in the audit log. Already-restricted lineages are not modified.
	// Clean lineages cannot be directly promoted — must touch a secret
	// first.
	PromoteOutboundRestricted(lineage uint64, at time.Time, reason string)

	// PromoteContainmentRequired escalates the lineage to the highest
	// state, triggering response-engine containment.
	PromoteContainmentRequired(lineage uint64, at time.Time, reason string)

	// InheritFromParent propagates parent taint to child on spawn. If
	// parent is clean, no-op. If parent is tainted, child inherits the
	// state and class set. Called from pipeline OnSpawn.
	InheritFromParent(parentLineage, childLineage uint64)

	// ForgetLineage clears all state for the lineage with an audited
	// reason. Returns true if the lineage was tainted before forget.
	ForgetLineage(lineage uint64, reason ForgetReason) bool

	// Size returns the number of tracked lineages (test/metrics helper).
	Size() int
}
