// Package cronclassify reads a cron entry (system /etc/cron.* file,
// /etc/crontab, or /var/spool/cron/crontabs/<user>) and returns a
// set of tag bits describing whether the entry shape looks like
// malware.
//
// The strategy: cron is real and used by every commodity Linux
// malware family (TeamTNT, Sysrv-Hello, Outlaw, Mirai variants),
// but root + package managers add cron entries every week as part
// of normal ops. Sandboxing every cron change is too expensive
// and noisy. Static pattern matching catches the 95% of real-
// world attack shapes for ~zero cost.
//
// Tag bits we stamp on the FIM event when it writes a cron path:
//
//	cron_shell_pipe       command pipes into a shell ( | bash, |sh)
//	cron_remote_fetch     command fetches over HTTP(S)/ftp/curl/wget
//	cron_b64              command contains base64 -d / openssl enc
//	cron_tmp_script       script resides under /tmp, /var/tmp, /dev/shm
//	cron_hidden_script    script under a hidden dir (~/.<x>, /.<x>)
//	cron_every_minute     schedule is * * * * * or */1
//	cron_added_by_web     file owner UID matches a web/service uid
//	cron_no_owner_comment no `# Edit this file ...` header → not crontab(1) origin
//
// Bits are independent; rules combine them. Defenders alert on
// the cluster (e.g. cron_shell_pipe && cron_tmp_script is near-
// certain malware).
package cronclassify

import (
	"bytes"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"syscall"
)

// Tags is the set of classifier outputs for one cron file.
type Tags map[string]string

var (
	rePipeShell    = regexp.MustCompile(`\|\s*(bash|sh|dash|zsh|ksh|ash)\b`)
	reRemoteFetch  = regexp.MustCompile(`(?i)\b(curl|wget|fetch)\b.*\bhttps?://|\bftp://`)
	reBase64       = regexp.MustCompile(`(?i)\b(base64\s+-d|openssl\s+enc\b|echo\s+["'][A-Za-z0-9+/=]{20,}["']\s*\|\s*base64)`)
	reTmpScript    = regexp.MustCompile(`(?:/tmp|/var/tmp|/dev/shm)/[^\s]+`)
	reHiddenScript = regexp.MustCompile(`\s/(?:[^/]+/)*\.[^/\s]+`)
	reEveryMinute  = regexp.MustCompile(`(?m)^\s*(?:\*|\*/1)\s+\*\s+\*\s+\*\s+\*\s`)
	reEvery2Min    = regexp.MustCompile(`(?m)^\s*\*/[123]\s+\*\s+\*\s+\*\s+\*\s`)
)

// webUserNames are the common web/service usernames. If the cron
// file's owning UID resolves to one of these (or any uid < 1000
// that isn't root), it's a near-certain indicator that an
// exploited web worker wrote the cron — legitimate cron drops by
// these users are vanishingly rare.
var webUserNames = map[string]bool{
	"www-data": true, "apache": true, "nginx": true, "httpd": true,
	"caddy": true, "php-fpm": true, "uwsgi": true,
	"gunicorn": true, "node": true, "haproxy": true,
	"mysql": true, "postgres": true,
}

// Classify reads path, inspects content + owner, returns tag bits.
// Missing file is not an error — returns empty map.
func Classify(path string) Tags {
	tags := Tags{}
	st, err := os.Stat(path)
	if err != nil {
		return tags
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return tags
	}

	// Owner-based signals.
	if sys, ok := st.Sys().(*syscall.Stat_t); ok {
		if name := lookupUID(sys.Uid); name != "" && webUserNames[name] {
			tags["cron_added_by_web"] = "true"
			tags["cron_owner"] = name
		}
		// Per-user crontab where owner UID doesn't match basename
		// is suspicious — crontab(1) chowns to the named user.
		if strings.HasPrefix(path, "/var/spool/cron/crontabs/") {
			base := filepath.Base(path)
			if owner := lookupUID(sys.Uid); owner != "" && owner != base {
				tags["cron_owner_mismatch"] = "true"
				tags["cron_basename"] = base
				tags["cron_owner"] = owner
			}
		}
	}

	// Content signals.
	text := string(data)
	if rePipeShell.MatchString(text) {
		tags["cron_shell_pipe"] = "true"
	}
	if reRemoteFetch.MatchString(text) {
		tags["cron_remote_fetch"] = "true"
	}
	if reBase64.MatchString(text) {
		tags["cron_b64"] = "true"
	}
	if m := reTmpScript.FindString(text); m != "" {
		tags["cron_tmp_script"] = "true"
		tags["cron_tmp_path"] = m
	}
	// Hidden-dir match must not also be a tmp/var/dev hit.
	if !strings.Contains(text, "/tmp") && reHiddenScript.MatchString(text) {
		tags["cron_hidden_script"] = "true"
	}
	if reEveryMinute.MatchString(text) {
		tags["cron_every_minute"] = "true"
	} else if reEvery2Min.MatchString(text) {
		tags["cron_every_few_min"] = "true"
	}
	// crontab(1)-managed files start with a header explaining
	// the file is auto-managed. Absence is a soft signal that
	// the file was written some other way (an attacker dropping
	// /var/spool/cron/crontabs/root directly via shell write).
	if strings.HasPrefix(path, "/var/spool/cron/crontabs/") &&
		!bytes.Contains(data, []byte("DO NOT EDIT THIS FILE")) &&
		!bytes.Contains(data, []byte("# Edit this file")) {
		tags["cron_no_owner_comment"] = "true"
	}
	return tags
}

// Suspicion returns a 0-100 risk score derived from the tag bits,
// useful for rule predicates that want a single threshold instead
// of enumerating combinations.
func Suspicion(tags Tags) int {
	score := 0
	weights := map[string]int{
		"cron_shell_pipe":       40,
		"cron_remote_fetch":     35,
		"cron_b64":              30,
		"cron_tmp_script":       30,
		"cron_hidden_script":    25,
		"cron_added_by_web":     50,
		"cron_owner_mismatch":   60,
		"cron_every_minute":     20,
		"cron_every_few_min":    10,
		"cron_no_owner_comment": 10,
	}
	for k, v := range weights {
		if tags[k] == "true" {
			score += v
		}
	}
	if score > 100 {
		score = 100
	}
	return score
}

// lookupUID returns the username for uid, or "" on failure.
// Bare /etc/passwd parse — avoids cgo, avoids os/user which would
// require nsswitch and slow the hot path.
var uidCache = map[uint32]string{}

func lookupUID(uid uint32) string {
	if name, ok := uidCache[uid]; ok {
		return name
	}
	data, err := os.ReadFile("/etc/passwd")
	if err != nil {
		return ""
	}
	for _, line := range strings.Split(string(data), "\n") {
		f := strings.Split(line, ":")
		if len(f) < 3 {
			continue
		}
		if f[2] == itoa(uid) {
			uidCache[uid] = f[0]
			return f[0]
		}
	}
	return ""
}

func itoa(u uint32) string {
	// avoid strconv import bloat for this tiny helper
	if u == 0 {
		return "0"
	}
	var b [10]byte
	i := len(b)
	for u > 0 {
		i--
		b[i] = byte('0' + u%10)
		u /= 10
	}
	return string(b[i:])
}
