// Package procfs generates the operator-visible artifacts that
// harden /proc against same-UID credential scraping:
//
//   - /etc/sysctl.d/60-xhelix-procfs.conf
//     Yama ptrace_scope=2, fs.suid_dumpable=0, hard/soft links restricted.
//
//   - /etc/systemd/system/<unit>.d/60-xhelix-procfs.conf
//     ProtectProc=invisible, ProcSubset=pid, NoNewPrivileges=yes for
//     declared consumer services (php-fpm, nginx, sshd-class workers,
//     anything an operator adds to a target list).
//
// Generation is pure (returns strings/maps). Apply is operator-gated
// in cmd/xhelixctl/posture_procfs.go — this package never writes to
// /etc on its own.
//
// Why these settings:
//
//   - hidepid is a mount-time option of /proc itself; setting it via
//     a sysctl drop-in does not work. systemd's ProtectProc=invisible
//     is the modern equivalent and is applied per-service.
//   - PR_SET_DUMPABLE is a per-process bit. fs.suid_dumpable=0
//     restricts core dumps + /proc/<pid>/mem cross-process reads for
//     setuid binaries; combined with NoNewPrivileges=yes per-service
//     it covers the majority of the surface.
//   - kernel.yama.ptrace_scope=2 denies cross-process attaches even
//     to same-UID processes without CAP_SYS_PTRACE.
package procfs

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

// SysctlContent returns the body of the xhelix procfs sysctl
// drop-in. Operators install it as
// /etc/sysctl.d/60-xhelix-procfs.conf and run `sysctl --system`.
func SysctlContent() string {
	return `# Managed by xhelix. Generated by ` + "`xhelixctl posture procfs generate`" + `.
# Hardens /proc against same-UID credential scraping. Reversible by
# removing this file and running 'sysctl --system'.

# Yama: deny ptrace(PTRACE_ATTACH) and process_vm_readv cross-process
# reads from non-CAP_SYS_PTRACE processes, even at the same UID.
kernel.yama.ptrace_scope = 2

# Core dumps + /proc/<pid>/mem for setuid binaries: deny.
fs.suid_dumpable = 0

# Restrict creation of hard/symbolic links so attackers cannot escape
# allowlist checks via path indirection.
fs.protected_hardlinks = 1
fs.protected_symlinks  = 1
fs.protected_fifos     = 2
fs.protected_regular   = 2
`
}

// SysctlPath is the conventional install destination.
const SysctlPath = "/etc/sysctl.d/60-xhelix-procfs.conf"

// DefaultTargets returns the set of systemd units xhelix will
// generate drop-ins for by default. These are the consumer-service
// classes that touch credentials on common Linux servers.
//
// Operators can extend via the --unit flag on
// `xhelixctl posture procfs generate`.
func DefaultTargets() []string {
	return []string{
		// Web/app workers — read .env, cloud SDK creds.
		"php-fpm.service",
		"php8.1-fpm.service",
		"php8.2-fpm.service",
		"php8.3-fpm.service",
		"nginx.service",
		"apache2.service",
		"httpd.service",
		// Database servers — credentials live in env or config.
		"mariadb.service",
		"mysql.service",
		"postgresql.service",
		"redis.service",
		// Plesk + cPanel control panels (best-effort; absence is fine).
		"sw-cp-server.service",
		"psa.service",
		// Generic CI/CD runners.
		"gitlab-runner.service",
	}
}

// DropInContent returns the per-service systemd drop-in body that
// hides other users' /proc entries from this service and blocks
// privilege escalation paths used to bypass procfs protection.
//
// The empty drop-in name matches the convention
// `60-xhelix-procfs.conf` under
// /etc/systemd/system/<unit>.d/.
func DropInContent(unit string) string {
	return `# Managed by xhelix. Generated by ` + "`xhelixctl posture procfs generate`" + `.
# Hardens ` + unit + ` against /proc cross-process credential reads.
# Reversible by removing this drop-in and running 'systemctl daemon-reload'.

[Service]
# /proc shows only this service's own PIDs + kernel threads.
ProtectProc=invisible

# Hide /proc subdirectories other than per-PID entries from the
# service. Same-UID processes outside this unit cannot enumerate.
ProcSubset=pid

# Block setuid escalation paths that bypass dumpable=0.
NoNewPrivileges=yes

# Belt + braces: kernel tunables become read-only for this service.
ProtectKernelTunables=yes
`
}

// DropInDir returns the conventional drop-in directory for a unit.
func DropInDir(unit string) string {
	return "/etc/systemd/system/" + unit + ".d"
}

// DropInPath returns the conventional drop-in file path.
func DropInPath(unit string) string {
	return DropInDir(unit) + "/60-xhelix-procfs.conf"
}

// Status reports the live host state of the settings the
// generator targets. Useful for `posture procfs status` so
// operators can see "applied" vs "missing" without diffing files.
type Status struct {
	PtraceScope     int    // /proc/sys/kernel/yama/ptrace_scope
	SuidDumpable    int    // /proc/sys/fs/suid_dumpable
	HardlinksProt   int    // /proc/sys/fs/protected_hardlinks
	SymlinksProt    int    // /proc/sys/fs/protected_symlinks
	SysctlInstalled bool   // SysctlPath exists
	UnitsWithDropIn []string
	UnitsMissing    []string
}

// ReadStatus inspects the live kernel + filesystem.
func ReadStatus(targets []string) Status {
	if targets == nil {
		targets = DefaultTargets()
	}
	st := Status{
		PtraceScope:   readInt("/proc/sys/kernel/yama/ptrace_scope"),
		SuidDumpable:  readInt("/proc/sys/fs/suid_dumpable"),
		HardlinksProt: readInt("/proc/sys/fs/protected_hardlinks"),
		SymlinksProt:  readInt("/proc/sys/fs/protected_symlinks"),
	}
	if _, err := os.Stat(SysctlPath); err == nil {
		st.SysctlInstalled = true
	}
	for _, u := range targets {
		if _, err := os.Stat(DropInPath(u)); err == nil {
			st.UnitsWithDropIn = append(st.UnitsWithDropIn, u)
		} else if unitExists(u) {
			st.UnitsMissing = append(st.UnitsMissing, u)
		}
	}
	sort.Strings(st.UnitsWithDropIn)
	sort.Strings(st.UnitsMissing)
	return st
}

// Summary returns a one-line human verdict for `posture procfs status`.
func (s Status) Summary() string {
	parts := []string{}
	if s.PtraceScope >= 2 {
		parts = append(parts, "ptrace_scope=ok")
	} else {
		parts = append(parts, fmt.Sprintf("ptrace_scope=%d(weak)", s.PtraceScope))
	}
	if s.SuidDumpable == 0 {
		parts = append(parts, "suid_dumpable=ok")
	} else {
		parts = append(parts, fmt.Sprintf("suid_dumpable=%d(weak)", s.SuidDumpable))
	}
	if s.SysctlInstalled {
		parts = append(parts, "sysctl=installed")
	} else {
		parts = append(parts, "sysctl=missing")
	}
	parts = append(parts, fmt.Sprintf("dropins=%d/%d",
		len(s.UnitsWithDropIn),
		len(s.UnitsWithDropIn)+len(s.UnitsMissing)))
	return strings.Join(parts, " ")
}

func readInt(path string) int {
	b, err := os.ReadFile(path)
	if err != nil {
		return -1
	}
	var n int
	if _, err := fmt.Sscanf(strings.TrimSpace(string(b)), "%d", &n); err != nil {
		return -1
	}
	return n
}

// unitExists is a best-effort check: a unit "exists" if
// /lib/systemd/system or /etc/systemd/system contains a file with
// that name. Operators can disagree (template units, runtime-only
// units) but for the default target list this is sufficient.
func unitExists(unit string) bool {
	for _, dir := range []string{
		"/etc/systemd/system/",
		"/lib/systemd/system/",
		"/usr/lib/systemd/system/",
	} {
		if _, err := os.Stat(dir + unit); err == nil {
			return true
		}
	}
	return false
}
