#!/usr/bin/env bash
# test-setup.sh — bootstrap xhelix in MONITOR (learning) mode on a
# Debian/Ubuntu test host. Idempotent — re-run is safe.
#
# Monitor mode = every subsystem WATCHES and SCORES but DOES NOT
# enforce. AppArmor profiles ship with flags=(complain). seccomp
# is NOT installed (so syscalls are observed via eBPF, not denied).
# response.Engine is wired but its policy entries are ActionLog
# only. takeover.Active=false so the planner's ActionPlans go to
# the journal as "planner shadow" lines without executing.
#
# WHY monitor mode: you wanted to see every functionality and its
# practical benefit. Enforcement would block the PoCs before
# xhelix could record what happens.
#
# Run: sudo bash scripts/test-setup.sh
# Re-run anytime; this script is idempotent.

set -euo pipefail

# ────────────────────────────────────────────────────────────────
# Config
# ────────────────────────────────────────────────────────────────
XHELIX_BIN="${XHELIX_BIN:-./xhelix}"
XHELIXCTL_BIN="${XHELIXCTL_BIN:-./xhelixctl}"
HONEYSH_BIN="${HONEYSH_BIN:-./xhelix-honeysh}"
SINKHOLE_BIN="${SINKHOLE_BIN:-./xhelix-sinkhole}"
DNSPOISON_BIN="${DNSPOISON_BIN:-./xhelix-dnspoison}"

STATE_DIR="${STATE_DIR:-/var/lib/xhelix}"
LOG_DIR="${LOG_DIR:-/var/log/xhelix}"
RUN_DIR="${RUN_DIR:-/run/xhelix}"
FORENSIC_DIR="${FORENSIC_DIR:-${STATE_DIR}/forensic}"
CONFIG_DIR="${CONFIG_DIR:-/etc/xhelix}"
CONFIG_FILE="${CONFIG_FILE:-${CONFIG_DIR}/xhelix.yaml}"

# ────────────────────────────────────────────────────────────────
# Helpers
# ────────────────────────────────────────────────────────────────
log()  { printf '\033[1;34m[setup]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[warn]\033[0m  %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[fail]\033[0m  %s\n' "$*" >&2; exit 1; }

need_root() {
    if [[ $EUID -ne 0 ]]; then
        die "must run as root: sudo bash $0"
    fi
}

check_binaries() {
    log "checking binaries"
    for bin in "$XHELIX_BIN" "$XHELIXCTL_BIN" "$HONEYSH_BIN" "$SINKHOLE_BIN" "$DNSPOISON_BIN"; do
        if [[ ! -x "$bin" ]]; then
            die "binary not found or not executable: $bin (run 'make build' first)"
        fi
    done
}

check_kernel() {
    log "checking kernel ≥ 5.15"
    local ver
    ver=$(uname -r | cut -d. -f1-2)
    local major minor
    IFS=. read -r major minor <<<"$ver"
    if (( major < 5 )) || { (( major == 5 )) && (( minor < 15 )); }; then
        warn "kernel ${ver} < 5.15 — some eBPF features may be missing"
    fi
}

check_lsm() {
    log "checking LSM features"
    if [[ -r /sys/kernel/security/lsm ]]; then
        local lsm
        lsm=$(cat /sys/kernel/security/lsm)
        if [[ "$lsm" == *bpf* ]]; then
            log "  BPF LSM available: $lsm"
        else
            warn "  BPF LSM NOT in cmdline ($lsm) — some hooks degraded"
        fi
        if [[ "$lsm" == *apparmor* ]]; then
            log "  AppArmor available"
        else
            warn "  AppArmor NOT enabled — Ring 1 path-level enforcement off"
        fi
    fi
}

setup_dirs() {
    log "creating state dirs"
    install -d -m 0750 -o root -g root "$STATE_DIR" "$LOG_DIR" "$RUN_DIR" "$FORENSIC_DIR" "$CONFIG_DIR"
    install -d -m 0755 "$CONFIG_DIR/conf.d"
}

write_config() {
    log "writing $CONFIG_FILE (monitor / learning mode)"
    if [[ -f "$CONFIG_FILE" ]]; then
        cp "$CONFIG_FILE" "$CONFIG_FILE.bak.$(date +%s)"
        log "  backed up existing config"
    fi
    cat > "$CONFIG_FILE" <<EOF
# xhelix MONITOR / LEARNING mode config — generated by scripts/test-setup.sh
# Every subsystem WATCHES and SCORES, nothing ENFORCES.
preset: server

logging:
  level: info
  format: text
  destination: stderr

agent:
  state_dir: $STATE_DIR
  log_dir: $LOG_DIR
  heartbeat_interval: 15s

storage:
  hot:
    path: $STATE_DIR/hot.db
    retention_hours: 24
    max_size_mb: 200
  cold:
    enabled: true

ruleset:
  bundled: true
  reload_on_change: true

alerts:
  severity_threshold: info     # surface everything
  sinks:
    - kind: stdout
    - kind: file
      path: /var/log/xhelix/alerts.jsonl
      rotate_size_mb: 100
      keep: 7
  rate_limit:
    per_rule_per_minute: 600
    global_per_second: 5000

# Response engine — monitor_mode forces every alert to ActionLog +
# ActionWebhook only. No quarantine, kill, netban, or remediate.
# Flip monitor_mode to false ONLY after auditing policy defaults for
# false-positive risk on your specific workload (see ERRORS.md
# "memfd self-DoS" entry).
response:
  enabled: true
  monitor_mode: true
  soak_days: 0

netban:
  enabled: false   # MONITOR — no bans
remediate:
  enabled: false
intel:
  enabled: true   # threat-intel lookups are read-only
chain:
  enabled: true   # signed evidence chain ON so xhelix-verify works

# Protected services — declared so the operator UX shows them,
# but with deception toggled OFF so PoCs aren't redirected.
# Flip deception flags individually below if you want to test
# specific Ring 2 layers without enabling refusal.
protected_services:
  enabled: true
  services:
    - name: nginx-test
      kind: nginx
      role: reverse_proxy
      unit: nginx.service
      exec_path: /usr/sbin/nginx
      cgroup_prefix: /system.slice/nginx.service
      contract:
        write_roots: ["/var/log/nginx", "/run/nginx", "/var/cache/nginx", "/tmp"]
        upstream_cidrs: ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
        strict_read_only: false  # MONITOR — let everything through
      response:
        deception:
          enabled: false       # MONITOR — don't redirect to honey-sh
          fake_exec: false
          sinkhole: false
          decoy_fs: false
          poison_dns: false

# Takeover planner — SHADOW MODE (active=false).
# The planner sees every alert, computes ActionPlans, and LOGS
# them ("planner shadow" lines in journalctl). Executor.Execute
# never runs.
takeover:
  active: false
  tick_interval: 5s
  min_score: 25       # lower threshold so even small attacks score

# Forensic JSON-lines ingest — ON.
forensic_ingest:
  enabled: true
  dir: $FORENSIC_DIR
  scan_interval: 5s
  poll_interval: 250ms

# Sensors — enabled for live-attack visibility. Most are off in
# Default(); presets only flip FIM. The eBPF sensor needs
# /usr/lib/xhelix/xhelix-progs.o (run \`make ebpf\` and deploy).
sensors:
  heartbeat:
    enabled: true
    interval: 1s
  ebpf:
    enabled: true
    ringbuf_size_mb: 16
  fim:
    enabled: true
    package_diff: true
    suid_baseline: true
    watch_paths:
      - /etc/passwd
      - /etc/shadow
      - /etc/sudoers
      - /etc/sudoers.d
      - /etc/cron.d
      - /etc/cron.daily
      - /etc/cron.hourly
      - /etc/cron.weekly
      - /etc/cron.monthly
      - /etc/crontab
      - /etc/systemd/system
      - /etc/ld.so.preload
      - /etc/pam.d
      - /root/.ssh
      - /home/*/.ssh
      - /etc/ssh
  decoys:
    enabled: true
  netids:
    enabled: true
  identity:
    enabled: true
  memory:
    enabled: true
  lsmaudit:
    enabled: true

# UI is OFF by default. Uncomment to enable at https://127.0.0.1:18443
# ui:
#   enabled: true
#   bind: 127.0.0.1:18443
#   tls_enabled: true
EOF
    chmod 0640 "$CONFIG_FILE"
}

kill_all_xhelix_daemons() {
    # P-PS.25: pkill against /usr/local/bin/xhelix doesn't match
    # daemons launched as ./xhelix (relative). Match the run command
    # invariant instead.
    local pids
    pids=$(pgrep -f 'xhelix run --config' 2>/dev/null || true)
    if [[ -n "$pids" ]]; then
        log "  killing existing xhelix daemons: $pids"
        # shellcheck disable=SC2086
        kill -TERM $pids 2>/dev/null || true
        sleep 2
        # Hard-kill anything still up
        pids=$(pgrep -f 'xhelix run --config' 2>/dev/null || true)
        if [[ -n "$pids" ]]; then
            # shellcheck disable=SC2086
            kill -9 $pids 2>/dev/null || true
            sleep 1
        fi
    fi
}

restart_xhelix() {
    log "restarting xhelix daemon"
    if systemctl is-active --quiet xhelix.service 2>/dev/null; then
        systemctl restart xhelix
        sleep 2
        if ! systemctl is-active --quiet xhelix.service; then
            warn "xhelix.service failed to start — check 'journalctl -u xhelix -n 50'"
        else
            log "  xhelix systemd unit running"
        fi
    else
        # No systemd unit — ensure singleton, then run in background
        kill_all_xhelix_daemons
        log "  no systemd unit found, starting xhelix in background"
        # Do NOT pre-write the pidfile: the daemon's own singleton
        # check (P-PS.25) reads the pidfile to detect a prior
        # instance. If we write our backgrounded pid here, the
        # daemon sees its own pid and refuses to start. The daemon
        # writes the pidfile itself after the singleton check.
        nohup "$XHELIX_BIN" run --config "$CONFIG_FILE" \
            > "$LOG_DIR/xhelix.out" 2>&1 &
        # Remember our $! for the immediate kill check below
        LAUNCHED_PID=$!
        sleep 3
        # Verify exactly ONE daemon is now running
        local count
        count=$(pgrep -cf 'xhelix run --config' 2>/dev/null || echo 0)
        if [[ "$count" != "1" ]]; then
            warn "  expected 1 xhelix daemon, found $count"
            pgrep -af 'xhelix run --config'
        fi
        if kill -0 "$LAUNCHED_PID" 2>/dev/null; then
            log "  xhelix running, pid $LAUNCHED_PID"
        else
            die "  xhelix failed to start — see $LOG_DIR/xhelix.out"
        fi
    fi
}

start_deception_binaries() {
    log "starting deception side-binaries (writing to $FORENSIC_DIR)"
    # honey-sh as a standalone is interactive; we don't pre-start it.
    # It's invoked per-session (manually or via bind-mount redirect).
    log "  honey-sh: invoke per session (interactive)"

    # Sinkhole on loopback ports (no root needed for >1024)
    if ! pgrep -f xhelix-sinkhole >/dev/null; then
        nohup "$SINKHOLE_BIN" \
            -http 127.0.0.1:8081 \
            -tls 127.0.0.1:8443 \
            -raw 127.0.0.1:14444 \
            -log "$FORENSIC_DIR/sinkhole.jsonl" \
            > "$LOG_DIR/sinkhole.out" 2>&1 &
        sleep 1
        log "  sinkhole: listening on 8081 / 8443 / 14444"
    else
        log "  sinkhole already running"
    fi

    # DNS poison on alt UDP port (53 needs root + free port)
    if ! pgrep -f xhelix-dnspoison >/dev/null; then
        # Empty known-bad list — DGA detector still active
        : > "$CONFIG_DIR/known-bad.txt"
        nohup "$DNSPOISON_BIN" \
            -udp 127.0.0.1:5353 \
            -known-bad "$CONFIG_DIR/known-bad.txt" \
            -log "$FORENSIC_DIR/dnspoison.jsonl" \
            > "$LOG_DIR/dnspoison.out" 2>&1 &
        sleep 1
        log "  dnspoison: listening on 127.0.0.1:5353"
    else
        log "  dnspoison already running"
    fi
}

print_status() {
    echo
    echo "════════════════════════════════════════════════════════════════"
    echo " xhelix MONITOR MODE — ready"
    echo "════════════════════════════════════════════════════════════════"
    echo
    echo "Operator surfaces:"
    echo "  $XHELIXCTL_BIN protect list"
    echo "  $XHELIXCTL_BIN protect deception"
    echo "  $XHELIXCTL_BIN forensic iocs"
    echo "  $XHELIXCTL_BIN posture lsm"
    echo
    echo "Live tail:"
    echo "  sudo journalctl -u xhelix -f"
    echo "    (or: tail -f $LOG_DIR/xhelix.out)"
    echo "  tail -F $FORENSIC_DIR/*.jsonl | jq ."
    echo
    echo "Run the PoC suite:"
    echo "  sudo bash tests/redteam/run_attack_suite.sh"
    echo
    echo "Remote attack simulation (separate host):"
    echo "  see tests/redteam/REMOTE_ATTACK.md"
    echo
    echo "Stop the deception side-binaries:"
    echo "  sudo pkill -f xhelix-sinkhole"
    echo "  sudo pkill -f xhelix-dnspoison"
    echo
}

# ────────────────────────────────────────────────────────────────
# Main
# ────────────────────────────────────────────────────────────────
need_root
check_binaries
check_kernel
check_lsm
setup_dirs
write_config
restart_xhelix
start_deception_binaries
print_status
